/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.todo.view;

import br.com.todo.NO.NoTarefa;
import br.com.todo.controller.TarefaController;
import br.com.todo.model.Util;
import java.time.LocalTime;
import javax.swing.JOptionPane;

/**
 *
 * @author kaior
 */
public class CadastroTarefa extends javax.swing.JPanel {

    TarefaController tController = new TarefaController();
    NoTarefa noT = new NoTarefa();
    //lista principal de tarefas
    NoTarefa.Lista lista = noT.new Lista();
    //lista principal de tarefas concluidas
    NoTarefa.ListaConcluida listaC = noT.new ListaConcluida();
    //instancia para receber a tela CadastroUser e acessar a lista principal de pessoas
    CadastroUser user;

    /**
     * Creates new form CadastroTarefa
     */
    public CadastroTarefa(CadastroUser user) {
        initComponents();
        this.user = user;
    }

    public CadastroUser getUser() {
        return user;
    }

    public NoTarefa getTarefa() {
        return noT;
    }

    public NoTarefa.Lista getLista() {
        return lista;
    }

    public NoTarefa.ListaConcluida getListaC() {
        return listaC;
    }

    //verifica se a pessoa já possui uma tarefa cadastrada naquele horario
    public boolean verificaHora(NoTarefa.Lista list, int codigo, LocalTime hora) {
        NoTarefa lista = list.getInicio();
        boolean horaLivre = true;
        while (lista != null) {
            if (lista.getTarefa().getPessoa().getCodigo() == codigo) {
                if (lista.getTarefa().getHoraTarefa().compareTo(hora) == 0) {
                    horaLivre = false;
                } else {
                    horaLivre = true;
                }
            }
            lista = lista.getProximo();
        }
        return horaLivre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelForm = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nomeTarefa = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        duracao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descTarefa = new javax.swing.JTextArea();
        dataTarefa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        horaTarefa = new javax.swing.JTextField();
        codigoResp = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelForm.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel5.setText("Código do responsável");

        nomeTarefa.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        nomeTarefa.setText("Tarefa teste");

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jButton2.setText("SALVAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel1.setText("Nome da tarefa");

        duracao.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        duracao.setText("01:00:00");

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel2.setText("Descrição da tarefa");

        jLabel6.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel6.setText("Duração");

        descTarefa.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        descTarefa.setLineWrap(true);
        descTarefa.setRows(5);
        descTarefa.setText("Descriao da tarefa teste");
        jScrollPane1.setViewportView(descTarefa);

        dataTarefa.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        dataTarefa.setText("2023-10-10");

        jLabel3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel3.setText("Data");

        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel4.setText("Hora");

        horaTarefa.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        horaTarefa.setText("15:00:00");

        codigoResp.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        codigoResp.setText("12345");

        javax.swing.GroupLayout jPanelFormLayout = new javax.swing.GroupLayout(jPanelForm);
        jPanelForm.setLayout(jPanelFormLayout);
        jPanelFormLayout.setHorizontalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeTarefa)
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(horaTarefa)
                            .addComponent(dataTarefa)
                            .addGroup(jPanelFormLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(54, 54, 54))
                            .addGroup(jPanelFormLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(53, 53, 53))))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(176, 176, 176))
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoResp)
                            .addGroup(jPanelFormLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(7, 7, 7)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFormLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(4, 4, 4))
                            .addComponent(duracao))))
                .addGap(49, 49, 49))
        );
        jPanelFormLayout.setVerticalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nomeTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addComponent(dataTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(horaTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(duracao)
                    .addComponent(codigoResp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //verifica se o usuário existe
        if (user.vCod(Integer.parseInt(codigoResp.getText()))) {
            JOptionPane.showMessageDialog(null, "Usuário não existe.");
        } else {
            //caso o usuário exista, é verificado se já possui uma tarefa naquele horário
            if (verificaHora(getLista(), Integer.parseInt(codigoResp.getText()), LocalTime.parse(horaTarefa.getText()))) {
                lista.inserirNoInicio(tController.cadastrar(this));
                descTarefa.setText("");
                new Util().LimpaTela(jPanelForm);
            } else {
                JOptionPane.showMessageDialog(null, "Usuário já possui tarefa nesse horario.");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField codigoResp;
    public javax.swing.JTextField dataTarefa;
    public javax.swing.JTextArea descTarefa;
    public javax.swing.JTextField duracao;
    public javax.swing.JTextField horaTarefa;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField nomeTarefa;
    // End of variables declaration//GEN-END:variables
}
