/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.todo.view;

import br.com.todo.NO.NoPessoa;
import br.com.todo.NO.QuickSort;

/**
 *
 * @author kaior
 */
public class UserList extends javax.swing.JPanel {

    CadastroUser user;

    /**
     * Creates new form UserList
     */
    public UserList(CadastroUser user) {
        initComponents();
        this.user = user;
    }

    //atualiza a lista de usuários
    public void atualizaLista() {
        //ordena a lista de usuários de acordo com a quantidade de atividades de cada um
        QuickSort.quicksortP(user.getLista());
        //cria um nó de pessoa que recebe o inicio da lista
        NoPessoa noP = user.getLista().getInicio();
        //limpa o painel lista
        lista.removeAll();
        if (user.getLista().getTamanho() > 10) {
            lista.setLayout(new java.awt.GridLayout(user.getLista().getTamanho(), 1));
        } else {
            lista.setLayout(new java.awt.GridLayout(10, 1));
        }
        //enquanto o nó de pessoa não for nulo, é adicionado uma tela com os dados da pessoa
        //e o nó recebe o proximo
        while (noP != null) {
            //dados de pessoa é adicionado na tela
            lista.add(new UserUni(noP), 0);
            //nó de pessoa recebe o próximo para continuar
            noP = noP.getProximo();
            lista.repaint();
            this.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        lista.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout listaLayout = new javax.swing.GroupLayout(lista);
        lista.setLayout(listaLayout);
        listaLayout.setHorizontalGroup(
            listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        listaLayout.setVerticalGroup(
            listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1162, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lista;
    // End of variables declaration//GEN-END:variables
}
