/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.todo.view.manager;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;

/**
 *
 * @author kaior
 */
public class Menu extends javax.swing.JPanel {

    ImageIcon icon = new ImageIcon("src/assets/todoLogo.png");
    String rota = "";
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        icon.setImage(icon.getImage().getScaledInstance(280, 105, 1));
        jIcon.setIcon(icon);
        jInicio.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                rota = "inicio";
            }
        });
    }

    public String getRota() {
        return rota;
    }

    public void setRota(String rota) {
        this.rota = rota;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jIcon = new javax.swing.JLabel();
        jInicio = new javax.swing.JLabel();
        jCadTarefa = new javax.swing.JLabel();
        jCadUser = new javax.swing.JLabel();
        jVerUsers = new javax.swing.JLabel();
        jExit = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jIcon.setToolTipText("");

        jInicio.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jInicio.setText("Inicio");
        jInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jCadTarefa.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jCadTarefa.setText("Cadastrar tarefa");
        jCadTarefa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jCadUser.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jCadUser.setText("Cadastrar usuário");
        jCadUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jVerUsers.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jVerUsers.setText("Ver usuários");
        jVerUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jExit.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jExit.setText("Sair");
        jExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton1.setText("USER: KAIO");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jInicio)
                            .addComponent(jCadTarefa)
                            .addComponent(jCadUser)
                            .addComponent(jExit)
                            .addComponent(jVerUsers))
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jInicio)
                .addGap(38, 38, 38)
                .addComponent(jCadTarefa)
                .addGap(38, 38, 38)
                .addComponent(jCadUser)
                .addGap(38, 38, 38)
                .addComponent(jVerUsers)
                .addGap(38, 38, 38)
                .addComponent(jExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jCadTarefa;
    private javax.swing.JLabel jCadUser;
    private javax.swing.JLabel jExit;
    private javax.swing.JLabel jIcon;
    private javax.swing.JLabel jInicio;
    private javax.swing.JLabel jVerUsers;
    // End of variables declaration//GEN-END:variables
}
